namespace SpriteKind {
    export const Wall = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ......................................................................
        .............1...................................................1....
        .............11.........111....................1................1.....
        ......111.....1...........1..................111......1111....11......
        ........11.....1....11....11................11.....111.......1........
        ..........111..11....11....11..............11....11...........11......
        ..111........11111....11....1.............11....11.........111.1......
        ....11..........111....1.....1............1...111........11...........
        .....111..........1111.11.................1.111........11.............
        .......1..........1...111.................111.......1111..111111111...
        ......1111111111111......11..................1...........11...........
        .............11...............................111......11.............
        ............11...................................1111.................
        .....111...11......11...............................111......11.......
        ....11.111..........111....................11.........111.....11......
        .........11.....1111111111..................11..........11......11....
        ..........1...111..1....1....1...............111.........11......11...
        ........1111111...11...11...1..................111....................
        .......11........11...11...11....................1111.................
        ................11....1....1........................11................
        `, Myplayer, 0, 0)
    pause(300)
    sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite = sprites.create(img`
        ................
        ................
        ................
        ................
        ...........dd...
        ........ddddd...
        .....ddddddd....
        ....ddfffddd....
        ....dfffffd.....
        ....dfffffdd....
        ....ddffffd.....
        .....dfffdd.....
        ...ffddfddff....
        ..fddddfddddf...
        .fdddddffddddf..
        .fddddddfddddf..
        .fdddddffddddf..
        .fdddddfdddddf..
        .fdddddfdddddf..
        .fddfddfdddfdf..
        .fddfddfddffdf..
        .fdfddffddfddf..
        .fdfddfddfdddf..
        ..fdddfddfddddf.
        `, SpriteKind.Player)
})
let mySprite: Sprite = null
let projectile: Sprite = null
let Myplayer: Sprite = null
Myplayer = sprites.create(img`
    ................
    ................
    ................
    ................
    ..dd............
    ..dddd..........
    ...ddddddd......
    ...ddffffdd.....
    ....dfffffd.....
    ....dfffffdd....
    ....ddffffd.....
    .....dfffdd.....
    ...ffddfddff....
    ..fddddfddddf...
    .fdddddffddddf..
    .fddddddfddddf..
    .fdddddffddddf..
    .fdddddfdddddf..
    .fdddddfdddddf..
    .fddfddfdddfdf..
    .fddfddfddffdf..
    .fdfddffddfddf..
    fddfddfddfdddf..
    ddfdddfddfddff..
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(Myplayer)
tiles.placeOnRandomTile(Myplayer, assets.tile`myTile1`)
Myplayer.setBounceOnWall(true)
controller.moveSprite(Myplayer)
