namespace SpriteKind {
    export const Wall = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ..................................................
        .............ddddddddddddd........................
        ..........dddddd1111111111........................
        ......dddddddd11111111111.........................
        .....dddd11111111.................................
        ....ddd1111111....................................
        ..dddd11111.......................................
        ..ddd11111........................................
        ..dd11111.........................................
        ..dd1111..........................................
        ..dd1111..........................................
        ..dd1111..........................................
        ..ddd1111.........................................
        ..ddd111111.......................................
        ...ddd111111......................................
        ....ddd111111.....................................
        ....dddd1111111...................................
        .....ddddd11111111................................
        .......ddddd111111111.............................
        ..........ddddddddddddd...........................
        `, Myplayer, 0, 0)
    pause(300)
    sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Myplayer = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . d d d . . . . . . . . . . 
        . . . d d d d d . . . . . . . . 
        . . . d d f f f d d . . . . . . 
        . . . . d f f f f f d . . . . . 
        . . . . d f f f f f d . . . . . 
        . . . . . d f f f f d . . . . . 
        . . . . . d d d d d . . . . . . 
        . . . . f f d d f d f f . . . . 
        . . f f d d d d f d d d f f . . 
        . . f d d d d d f d d d d f . . 
        . . f d d d d d f d d d d f . . 
        . . f d d f d d f d d f d f . . 
        . . f d d f d d f d d f d f . . 
        . . f d d f d d f d d f d f . . 
        . . f d f d d f d d f d d f . . 
        `, SpriteKind.Player)
})
let projectile: Sprite = null
let Myplayer: Sprite = null
Myplayer = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . d d . . . . 
    . . . . . . . . d d d d . . . . 
    . . . . . d d d d d d . . . . . 
    . . . . d d f f f d d . . . . . 
    . . . . d f f f f d . . . . . . 
    . . . . d f f f f d . . . . . . 
    . . . f d f f f d f . . . . . . 
    . . f d f d d d f d f . . . . . 
    . f d d d f f f d d f f . . . . 
    . f d d d d f d d d d f . . . . 
    . f d d d d f d d d d f . . . . 
    . f d d d d f d f d d f . . . . 
    . f d d f d f d f d d f . . . . 
    . d f d f d f d d f d d f . . . 
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(Myplayer)
tiles.placeOnRandomTile(Myplayer, assets.tile`myTile5`)
controller.moveSprite(Myplayer)
Myplayer.setBounceOnWall(true)
let enemy_1 = sprites.create(img`
    ............................
    .......f...........f........
    .......fff.......fff........
    ........fdfffffffdf.........
    ........fffdddddfff.........
    .........fdfdddfdf..........
    .........fddfdfddf..........
    .........fdddfdddf..........
    .........fdddfdddf..........
    .........fdddfdddf..........
    ..........fddfddf...........
    ...........ffdff............
    ......f..fffdddfff..f.......
    ......fffffdddddfffff.......
    ......ffdddfdddfdddff.......
    ......fdddfdfdfdfdddf.......
    ......fdddfddfddfdddf.......
    ......fdddfdfffdfdddf.......
    ......fddfdddddddfddf.......
    ......fddfdfdddfdfdff.......
    ......fddfddfffddfddf.......
    ......fddfdddddddfddf.......
    ......fddfdfdddfdfddf.......
    ......fddfddfffddfddf.......
    ......fddfdddddddfddf.......
    ......fddfdfdddfdfddf.......
    .....fdddfddfffddfdddf......
    .....ffff.ff...ff.ffff......
    `, SpriteKind.Player)
tiles.placeOnRandomTile(enemy_1, assets.tile`myTile0`)
enemy_1.follow(Myplayer, 25)
