namespace SpriteKind {
    export const Wall = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ......................................................................
        .............1...................................................1....
        .............11.........111....................1................1.....
        ......111.....1...........1..................111......1111....11......
        ........11.....1....11....11................11.....111.......1........
        ..........111..11....11....11..............11....11...........11......
        ..111........11111....11....1.............11....11.........111.1......
        ....11..........111....1.....1............1...111........11...........
        .....111..........1111.11.................1.111........11.............
        .......1..........1...111.................111.......1111..111111111...
        ......1111111111111......11..................1...........11...........
        .............11...............................111......11.............
        ............11...................................1111.................
        .....111...11......11...............................111......11.......
        ....11.111..........111....................11.........111.....11......
        .........11.....1111111111..................11..........11......11....
        ..........1...111..1....1....1...............111.........11......11...
        ........1111111...11...11...1..................111....................
        .......11........11...11...11....................1111.................
        ................11....1....1........................11................
        `, Myplayer, 0, 0)
    pause(300)
    sprites.destroyAllSpritesOfKind(SpriteKind.Projectile)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile7`, function (sprite, location) {
    info.changeLifeBy(-1)
})
let projectile: Sprite = null
let Myplayer: Sprite = null
Myplayer = sprites.create(img`
    ................
    ................
    ................
    ................
    ..dd............
    ..dddd..........
    ...ddddddd......
    ...ddffffdd.....
    ....dfffffd.....
    ....dfffffdd....
    ....ddffffd.....
    .....dfffdd.....
    ...ffddfddff....
    ..fddddfddddf...
    .fdddddffddddf..
    .fddddddfddddf..
    .fdddddffddddf..
    .fdddddfdddddf..
    .fdddddfdddddf..
    .fddfddfdddfdf..
    .fddfddfddffdf..
    .fdfddffddfddf..
    fddfddfddfdddf..
    ddfdddfddfddff..
    `, SpriteKind.Player)
let Wallblock = sprites.create(img`
    c c c c c c c c c c c c c c c c 
    c b b b b b b b b c b b b b b b 
    c b b b b b b b b c b b b b b b 
    c b b b b b b b b c c b b b b b 
    c c c c c c c c c c c c c c c c 
    c b b b b b b c c b b b b b b b 
    c b b b b c c c b b b b b b b c 
    c c c c c c c c c c c c c c c c 
    b b b b b b b b c c c b b b b b 
    c b b b b b b b b b b c c c c b 
    c c c c c c c c c c c c c c c c 
    c b b b b b c c c b b b b b b b 
    b c c c c c b b b b b b c c c c 
    c c c c c c c c c c c c c c c c 
    c b b b b b b b c c c c c c c c 
    c c c c c c c c b b b b b b b c 
    `, SpriteKind.Wall)
let Enemyhurtyou = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 2 2 2 2 2 2 2 2 . . . . 
    . . . . 2 9 9 9 9 9 2 2 . . . . 
    . . . . 2 9 9 9 9 9 2 2 2 . . . 
    . . . . 2 9 9 9 9 9 2 2 2 2 2 . 
    . . . . 2 2 2 2 2 2 2 2 2 2 2 . 
    . . . . 2 2 2 2 2 2 2 2 2 2 2 . 
    . . . . 2 2 2 2 2 2 2 2 2 2 2 . 
    . . . 2 2 2 2 2 2 2 2 2 2 2 2 . 
    . . . 2 2 2 2 2 2 2 2 2 2 2 . . 
    . . . 2 2 2 2 2 2 2 2 2 2 . . . 
    . . . . 2 2 2 . . . 2 2 2 2 . . 
    . . . . 2 2 2 . . . 2 2 2 2 . . 
    . . . . 2 2 2 . . . . 2 2 2 . . 
    . . . . 2 2 2 . . . . 2 2 2 . . 
    `, SpriteKind.Enemy)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(Myplayer)
tiles.placeOnRandomTile(Myplayer, assets.tile`myTile3`)
tiles.placeOnRandomTile(Enemyhurtyou, assets.tile`myTile3`)
Enemyhurtyou.follow(Myplayer)
Myplayer.setBounceOnWall(true)
controller.moveSprite(Myplayer)
info.setLife(3)
